apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270wynterservice
spec:
  replicas:
  selector:
    matchLabels:
      app: cit270wynterservice
  template:
    metadata:
      name: cit270wynterservice
      labels:
        app: cit270wynterservice
    spec:
      containers:
        - name: cit270wynterservice
        image: united-aviary-379820/wynter-api
        volumeMounts:
         - name: ssl
            mountPath: "/etc/letsencrypt/live/SSL"
          command: ['npm']
          args: ["run","start"]
          resources:
            requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
       - name: ssl
        secret:
          secretName: wyntercerts